/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bankmanagmentsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Eldoran
 */
public class MainForm extends javax.swing.JFrame {
   private Controller controller;
   

   private int ID;
    
    /**
     * Creates new form MainForm
     */
    public MainForm(Controller controller,int AccountID) {
        this.controller = controller;
        this.ID = AccountID;
        initComponents();
        accountBalanceLabel.setEditable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accountBalanceLabel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        closeAccountButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        changePINButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Current Balance:");

        accountBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountBalanceLabel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        accountBalanceLabel.setText("0");
        accountBalanceLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceLabelActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setText("DEPOSIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        closeAccountButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        closeAccountButton.setText("CLOSE ACCOUNT");
        closeAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAccountButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton3.setText("WITHDRAW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        changePINButton.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        changePINButton.setText("CHANGE PIN");
        changePINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePINButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton4.setText("LOG OUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePINButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accountBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(changePINButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountBalanceLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceLabelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        double amountToBeAdded = 0;
        String input = JOptionPane.showInputDialog(null, "Enter an ammount:", "Input", JOptionPane.QUESTION_MESSAGE);
            // Check if the user clicked "Cancel" or closed the dialog
            if (input != null) {
                 // Validate that the input is a number
                if (input.matches("[-+]?\\d*\\.?\\d+")) {
                    try {
                        // Convert the input string to a double
                        amountToBeAdded = Double.parseDouble(input);
                        // Use the double value (e.g., print it)
                        
                    } catch (NumberFormatException e) {
                         // This catch block may never be reached due to the prior regex check
                         JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
                     }
                } else {
                     // If the input is not a valid number
                    JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;  // Exit the method if input is invalid
                }
            } else {
                // User canceled the input
                return;
            }
        String result = controller.addBalance(controller.loggedInAccount, amountToBeAdded);
        if (result.contains("successfully")){
            JOptionPane.showMessageDialog(null, result, "WITHDRAW", JOptionPane.INFORMATION_MESSAGE);
            //set the textlabel to show updated acocunt balance 
            accountBalanceLabel.setText(Double.toString(controller.loggedInAccount.getAccountBalance()));
            
        }else JOptionPane.showMessageDialog(null, result, "WITHDRAW", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAccountButtonActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to close your account?","Be Advised",JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION){
           //check the account
           if (controller.loggedInAccount.getAccountBalance() != 0.0){
               JOptionPane.showMessageDialog(null, "Account Balance must be 0","Closed Account", JOptionPane.INFORMATION_MESSAGE);
               return;
           }
           String result =  controller.closeAccount();
           if (result.contains("successfully")){
               JOptionPane.showMessageDialog(null, result,"Closed Account", JOptionPane.INFORMATION_MESSAGE);
               LogInForm loginForm= new LogInForm(controller);
               loginForm.setVisible(true);
               dispose();
           }else JOptionPane.showMessageDialog(null, result,"Closed Account", JOptionPane.ERROR_MESSAGE);

        }else return;
        
      
        // Account Balance must be 0;
        
        
    }//GEN-LAST:event_closeAccountButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:   
        double amountToBeDeducted = 0;
        String input = JOptionPane.showInputDialog(null, "Enter an ammount:", "Input", JOptionPane.QUESTION_MESSAGE);
            if (input.length() < 3){         //checks if the input was 3 digits or more
                JOptionPane.showMessageDialog(null, "Invalid input. Withdraw input must be divisble by 100.", "Error", JOptionPane.ERROR_MESSAGE);
                return ; 
            }
           

            // Check if the user clicked "Cancel" or closed the dialog
            if (input != null) {
                 // Validate that the input is a number
                if (input.matches("[-+]?\\d*\\.?\\d+")) {
                    try {
                        // Convert the input string to a double
                        amountToBeDeducted = Double.parseDouble(input);
                        if (amountToBeDeducted % 100 != 0) {
                            JOptionPane.showMessageDialog(null, "Invalid input. Withdraw input must be divisble by 100.", "Error", JOptionPane.ERROR_MESSAGE);
                         return;   
                        }
                    } catch (NumberFormatException e) {
                         // This catch block may never be reached due to the prior regex check
                         JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
                     }
                } else {
                     // If the input is not a valid number
                    JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;  // Exit the method if input is invalid
                }
            } else {
                // User canceled the input
                return;
            }
        String result = controller.reduceBalance(controller.loggedInAccount, amountToBeDeducted);
        if (result.contains("successfully")){
            JOptionPane.showMessageDialog(null, result, "WITHDRAW", JOptionPane.INFORMATION_MESSAGE);
            //set the textlabel to show updated acocunt balance 
            accountBalanceLabel.setText(Double.toString(controller.loggedInAccount.getAccountBalance()));
            
        }else JOptionPane.showMessageDialog(null, result, "WITHDRAW", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        controller.logInAccount(ID);
        accountBalanceLabel.setText(Double.toString(controller.loggedInAccount.getAccountBalance()));
        
        //check if PIN is default, if yes must change the PIN
        if(controller.loggedInAccount.getPIN() == 123456){
           int response = JOptionPane.showConfirmDialog(null,"Your using the default PIN \n Please Change your PIN","Be Advised",JOptionPane.OK_CANCEL_OPTION);
           if (response == JOptionPane.OK_OPTION){
               changePINButton.doClick();
           }else return;
           
            
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void changePINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePINButtonActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(null, "Enter your new PIN:", "Input", JOptionPane.QUESTION_MESSAGE);
        //checks if digit only and 6 digit
        
        if (input == null){  
            return; 
        }
        
        if (!input.matches("[-+]?\\d*\\.?\\d+")){  
            JOptionPane.showMessageDialog(null,"PIN must be a number only","Change PIN",JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (input.length() <= 5){
           JOptionPane.showMessageDialog(null,"PIN must be 6 digits or more","Change PIN",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String input2 = JOptionPane.showInputDialog(null, "Verify your new PIN: ", "Input", JOptionPane.QUESTION_MESSAGE);
        if (input2 == null){  
            return; 
        }
        if(!input2.equals(input) ){
            JOptionPane.showMessageDialog(null," PIN Change error! \n You entered a wrong PIN, it must be the same as the new PIN","Verify PIN",JOptionPane.ERROR_MESSAGE);
            return; 
        }
        //parsae the string to int then change the PIN
        int newPIN = Integer.parseInt(input);
        
        String result =  controller.changePin(newPIN);
        
        if (result.contains("Successfull")){
            JOptionPane.showMessageDialog(null,result,"Change PIN",JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(null,"Error Changing PIN","Change PIN",JOptionPane.ERROR_MESSAGE);
        LogInForm loginForm  = new LogInForm(controller);
        loginForm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_changePINButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Aryou sure you want to Log Out?", "Log Out",JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
           LogInForm loginForm  = new LogInForm(controller);
           loginForm.setVisible(true);
            dispose(); 
        }else return;
        
    }//GEN-LAST:event_jButton4ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountBalanceLabel;
    private javax.swing.JButton changePINButton;
    private javax.swing.JButton closeAccountButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
